services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5050:5050"
    networks:
      - app-network
    container_name: game-server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    container_name: game-client
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge