# Dockerfile.server
FROM gcc:latest

WORKDIR /server

# Copia i file del server
COPY server/ .
RUN gcc main.c partita.c richiesta.c coda.c -o main -pthread

# Esponi la porta su cui il server ascolta
EXPOSE 5050

# Comando per eseguire il server
CMD ["./main"]
